# Generated by Django 3.2 on 2021-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('actualidade', 'Actualidade')], default='', max_length=20),
        ),
    ]
